### ISSUE TITLE
There are no songs in playlist created based on PP

### ISSUE THREAD

**Issue by DetegiCE** [aplulu/bs-ranked-playlist#1]
<img width="561" alt="Screen Shot 2021-08-14 at 21 37 13" src="https://user-images.githubusercontent.com/26007107/129446560-0e236fef-054f-4572-892c-0705c3e19118.png">

Looks like there is an issue in BeatSaver

**Comment by aplulu** [comment]
Currently, the SongDataCore data used to generate the playlist does not contain pp correctly.
It may take some time to resolve this issue.
