### ISSUE TITLE
Playlistの一部が曲数0になっている

### ISSUE THREAD

**Issue by Fukutaro-dev** [aplulu/bs-ranked-playlist#4]
## 現象
![Playlist_cap](https://user-images.githubusercontent.com/80106416/130307259-0c68c7e0-d7f4-468a-a997-f00079c4f2fb.png)

## 再現手順
1. Latestからranked_all.zipをDL
2. 解凍
3. 「Playlist」フォルダに移動
4. Beatsaber起動
5. 曲が表示されなかったため、BeatListでも確認

## コメント
いつもお世話になっております、大変助かっております。
上記現象を確認しましたのでご報告させていただきました。
自環境のみで発生、手順の不手際、仕様変更の見逃しであれば良いのですが・・・

**Comment by ChrisJAllan** [comment]
原因はこっち：https://github.com/halsafar/BeatSaberSongDataCore/issues/12

**Comment by Fukutaro-dev** [comment]
@ChrisJAllan 
調査ありがとうございます。
対応に若干難航しているようですが、気長に待つこととします。

**Comment by Fukutaro-dev** [comment]
@ChrisJAllan 
latestで修正確認しました、ありがとうございました。
![image](https://user-images.githubusercontent.com/80106416/130600936-b78adb63-45df-4312-be7e-37af56e84651.png)
